name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate Makefiles
      run: cd cmake; cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - name: Generate package
      run: cd cmake; make package
